version: "3.7"

services:
    sqlserver:
        image: aspnetcore/mentoring_db
        container_name: mentoring_db
        build:
            context: .
            dockerfile: Mssql.Dockerfile
        ports:
            - "1433:1433"
        expose:
            - 1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_PID=Express
            - SA_PASSWORD=@Batoan01326754@
        # volumes:
        #     - ./Db:/home/data/
        #     # - ./Bk:/home/backup/
        #     - ./Log:/home/log/
        
