version: "3.7"

services:
    sqlserver:
        image: aspnetcore/mentoring_db
        container_name: mentoring_db
        build:
            context: .
            dockerfile: Mssql.Dockerfile
        ports:
            - "1433:1433"
        expose:
            - 1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_PID=Express
            - SA_PASSWORD=@Batoan01326754@
        volumes:
            - ./Db:/var/opt/mssql/data
            # - ./Bk:/home/backup/
            - ./Log:/var/opt/mssql/log
            - ./docker-db-init.sh:/db-init.sh
            - ./docker-db-init.sql:/db-init.sql
            - ./docker-entrypoint.sh:/entrypoint.sh
        
